### ISSUE TITLE
feature/split_module_2: AttributeError: 'module' object has no attribute 'is_main_thread'

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1000]
utils :  v0.40-22-g15e37d4@fix-log_fs_handler
saga  : v0.40.1-19-gec45d2e@devel
pilot : v0.40.1-79-gd871684@feature-split_module_2

00_getting_started.py example:

```
wait for 128 unit(s)
        ***********************************************************************|
        ********************************************************************** ok
********************************************************************************|
        ***********************************                                   ok

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.antons-pc.antons.016909.0000                        \
close unit manager                                                             \
wait for 128 unit(s)
                                                                         timeout
Traceback (most recent call last):
  File "00_getting_started.py", line 121, in <module>
    session.close()
  File "/home/antons/v16/local/lib/python2.7/site-packages/radical/pilot/session.py", line 353, in close
    umgr.close()
  File "/home/antons/v16/local/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 183, in close
    self._controller.stop()
  File "/home/antons/v16/local/lib/python2.7/site-packages/radical/pilot/utils/controller.py", line 231, in stop
    if not ru.is_main_thread():
AttributeError: 'module' object has no attribute 'is_main_thread'
```

**Comment by antonst** [comment]
No CUs were executed

**Comment by andre-merzky** [comment]
Thanks Antons -- can you please pull RU from the `fix/log_fs_handler` branch?  I pushed a commit which should fix this.

Best, Andre.

**Comment by antonst** [comment]
I tried Andre. still don't see CUs running. Terminal output is:
```
2016-04-18 21:03:34,069: radical.saga.pty    : pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: WARNING : flush: [  139] [    1] (discard data: '
')
2016-04-18 21:03:34,171: radical.saga.cpi    : pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : run_sync: STATS 12079.0
2016-04-18 21:03:34,171: radical.saga.pty    : pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : write: [  139] [   14] (STATS 12079.0\n)
2016-04-18 21:03:34,175: radical.saga.pty    : pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : read : [  139] [  126] (OK\nSTATE : FAILED\n\nSTART  : 1461027796\nSTOP   : 1461027804\n\nSTART_STDERR\n\nEND_STDERR\n\nSTART_STDOUT\n\nEND_STDOUT\n\n)
2016-04-18 21:03:34,176: radical.saga.pty    : pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : read : [  139] [   12] (PROMPT-0->\n)
2016-04-18 21:03:34,177: radical.saga.cpi    : pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : ['OK', 'STATE : FAILED', 'START  : 1461027796', 'STOP   : 1461027804', 'START_STDERR', 'END_STDERR', 'START_STDOUT', 'END_STDOUT']
2016-04-18 21:03:34,450: radical.saga.cpi    : pmgr.launching.0                : Thread-2       : DEBUG   : stop monitoring
2016-04-18 21:03:34,460: radical.saga.cpi    : pmgr.launching.0                : Thread-1       : DEBUG   : stop monitoring
2016-04-18 21:03:35,079: radical.saga.cpi    : pmgr.launching.0                : Thread-3       : DEBUG   : stop monitoring
                                                                              ok
2016-04-18 21:03:36,201: radical.pilot       : MainProcess                     : MainThread     : ERROR   : delete session
session lifetime: 24.0s                                                       ok
```

**Comment by antonst** [comment]
In agent_0.err I get:
```
Traceback (most recent call last):
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/bin/radical-pilot-agent", line 44, in <module>
    rp.agent.bootstrap_3()
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 24, in bootstrap_3
    agent_0 = Agent_0()
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 80, in __init__
    ru.dict_merge(cfg, self._session.ctrl_cfg, ru.PRESERVE)
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 206, in ctrl_cfg
    self._create_controller()
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 231, in _create_controller
    self._controller = rpu.Controller(cfg=self._cfg, session=self)
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/controller.py", line 163, in __init__
    self._log   = self._session._get_logger(self.uid, self._debug)
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 476, in _get_logger
    log = ru.get_logger(name, '.', self._logdir, level)
  File "/home/antons/radical.pilot.sandbox/rp.session.antons-pc.antons.016910.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/logger.py", line 254, in get_logger
    level = level.upper()
AttributeError: 'int' object has no attribute 'upper'
```

**Comment by andre-merzky** [comment]
Hmm, I feel like I have applied that fi now the third time or so :P  Either way, it has been pushed to the same branch.  Sorry for the troubles!

**Comment by antonst** [comment]
Seems to work now. I am getting this:
```
2016-04-18 21:54:55,624: radical.pilot       : MainProcess                     : MainThread     : ERROR   : delete session
```

at the end, which is a bit confusing.

**Comment by antonst** [comment]
Also in the log I don't see CU states being reported. I run with:
```
export RADICAL_PILOT_VERBOSE=INFO;
export SAGA_VERBOSE=INFO;
export RADICAL_VERBOSE=INFO; 
``` 

Am I doing something wrong?

**Comment by antonst** [comment]
example 01_unit_details.py after all CUs are done prints: ```caught Exception: 'working_directory'```
and then hangs.

**Comment by andre-merzky** [comment]
The `delete session` error was caused by an incorrect log level, that is fixed now.

The `working_directory` error you see seems to indicate something more serious -- the CU dict seems incomplete.  Would you mind sending me a tarball of the log files, both from client and agent side of things?  The client side log files are now in a subdir with the name of session ID.

Thanks!

**Comment by antonst** [comment]
Log files sent.... via e-mail

**Comment by andre-merzky** [comment]
Antons, I am closing this one in favor of the repex test problem.
