### ISSUE TITLE
Problem running example scripts on localhost (Workflow machine)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1078]
When I ssh in a workflow machine, I am unable to run scripts where the resource is set to localhost. Below is the error I encounter:

```
2016-07-13 12:36:01,713: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh
Copying bootstrapper 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x31e1810>).
Copying sdist 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/radical/utils/radical.utils-0.41.1.tar.gz' to sandbox (file://localhost/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0005-pilot.0000/).
Copying sdist 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/saga/saga-python-0.41.1.tar.gz' to sandbox (file://localhost/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0005-pilot.0000/).
Copying sdist 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-v0.40.3-12-gb280097-tutorial-xsede16.tar.gz' to sandbox (file://localhost/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0005-pilot.0000/).
Writing agent configuration to file '/tmp/rp_agent_cfg_dirDtieei/agent_0.cfg'.
Copying agent configuration file 'file://localhost/tmp/rp_agent_cfg_dirDtieei/agent_0.cfg' to sandbox (file://localhost/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0005-pilot.0000/).
Submitting SAGA job with description: {'Project': None, 'Executable': '/bin/bash', 'TotalPhysicalMemory': None, 'WorkingDirectory': '/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0005-pilot.0000/', 'Queue': None, 'Environment': {}, 'WallTimeLimit': 15, 'Arguments': ['-l bootstrap_1.sh', " -d 'radical.utils-0.41.1.tar.gz:saga-python-0.41.1.tar.gz:radical.pilot-v0.40.3-12-gb280097-tutorial-xsede16.tar.gz' -m 'create' -p 'pilot.0000' -r 'debug' -s 'rp.session.workflow.iu.xsede.org.mingtha.016995.0005' -v '/home/mingtha/radical.pilot.sandbox/ve_localhost' -b 'default' -a 'multicore'"], 'ProcessesPerHost': None, 'Error': 'bootstrap_1.err', 'Output': 'bootstrap_1.out', 'CandidateHosts': None, 'TotalCPUCount': 64}
Pilot launching failed! (failed to get valid job state for '[fork://localhost/]-[8082.0]' (['/home/mingtha/.saga/adaptors/shell_job/wrapper.sh: line 936: /tmp/t: Permission denied', 'OK', 'STATE : RUNNING', 'START  : 1468427761', 'START_STDERR', 'END_STDERR', 'START_STDOUT', 'END_STDOUT']) (/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +759 (_job_get_stats)  :  raise saga.NoSuccess ("failed to get valid job state for '%s' (%s)" % (id, lines))))
Traceback (most recent call last):
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 791, in run
    if pilotjob.state == saga.FAILED:
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/job/job.py", line 624, in get_state
    return self._adaptor.get_state (ttype=ttype)
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 1403, in get_state
    stats = self.js._job_get_stats (self._id)
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 759, in _job_get_stats
    raise saga.NoSuccess ("failed to get valid job state for '%s' (%s)" % (id, lines))
NoSuccess: failed to get valid job state for '[fork://localhost/]-[8082.0]' (['/home/mingtha/.saga/adaptors/shell_job/wrapper.sh: line 936: /tmp/t: Permission denied', 'OK', 'STATE : RUNNING', 'START  : 1468427761', 'START_STDERR', 'END_STDERR', 'START_STDOUT', 'END_STDOUT']) (/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +759 (_job_get_stats)  :  raise saga.NoSuccess ("failed to get valid job state for '%s' (%s)" % (id, lines)))
2016-07-13 12:36:01,983: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
2016-07-13 12:36:01,983: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 236, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1
```

From the agent logs, I found that agent_0.err contains the following:
`Exception KeyError: KeyError(140303046620992,) in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored`

**Comment by andre-merzky** [comment]
Hi Ming -- this problem should already be fixed.  What version or branch are you using?

**Comment by mingtaiha** [comment]
I am using the tutorial-xsede16 branch

**Comment by andre-merzky** [comment]
Ah, I am sorry, I should have asked for the SAGA version.  It is fixed on pypi - please reinstall SAGA, and you should end up with 0.41.3 which contains the fix.

**Comment by mingtaiha** [comment]
I ran the command `pip install --upgrade saga-python` and got the version 0.41.3. However, I still encounter this error. This error persisted even when I removed `radical.pilot.sandbox`, the virtualenv, and installed the entire setup from scratch.

**Comment by andre-merzky** [comment]
That is ... unexpected.  Is that on the workflow machine?

A.

**Comment by andre-merzky** [comment]
Ah, sorry - it is, you said so.  Let me have a look...

**Comment by andre-merzky** [comment]
Found it.  Would you please remove /home/mingtha/.saga/adaptors/shell_job/wrapper.sh and try again?  You don't need to reinstall...

**Comment by mingtaiha** [comment]
The code works! Balance is restored to the universe.

**Comment by marksantcroos** [comment]
Could this still happen to tutorial attendees too?

**Comment by andre-merzky** [comment]
Fortunately not, since `.saga/` will not exist in the accounts of new users, and the install will picked up the fixed version.
