### ISSUE TITLE
Probing example failing with key argument not in schema

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2170]
This issue is related to issue  #2114 regarding the RP example cleanup. 

```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aymen/ve/env

  radical.analytics    : 0.90.7
  radical.pilot        : 1.4.1
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0
```

The probing example failing with the following errors
From the CMD log:

```
if k not in schema: raise TypeError('key %s not in schema' % k)
TypeError: key argument not in schema
```

From the log files:
```
rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0003.log:1592928248.030 : rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0003 : 13248 : 140175144707840 : ERROR    : unusable lm MPIRUN
rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0003.log:1592928256.218 : rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0003 : 12945 : 140243726477056 : ERROR    : ResourceManager shutdown hook failed: cannot import name 'FLUX' from 'radical.pilot.agent.launch_method.flux' (/home/aymen/radical.pilot.sandbox/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0003/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/flux.py)
``` 

Below is the session folder:
[rp.session.js-17-185.jetstream-cloud.org.aymen.018436.000.zip](https://github.com/radical-cybertools/radical.pilot/files/4820638/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.000.zip)

**Comment by mtitov** [comment]
it is already fixed in [devel-branch](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/base.py#L243), but not yet in master

**Comment by AymenFJA** [comment]
OK, let me verify and update the ticket. Thanks @mtitov

**Comment by AymenFJA** [comment]
@mtitov still getting the same error:
```
Traceback (most recent call last):
  File "probing.py", line 101, in <module>
    umgr.submit_units(cuds)
  File "/home/aymen/rp/lib/python3.7/site-packages/radical/pilot/unit_manager.py", line 825, in submit_units
    unit = ComputeUnit(umgr=self, descr=ud)
  File "/home/aymen/rp/lib/python3.7/site-packages/radical/pilot/compute_unit.py", line 61, in __init__
    descr.verify()
  File "/home/aymen/rp/lib/python3.7/site-packages/radical/utils/description.py", line 234, in verify
    return super(Description, self).verify(self._schema)
  File "/home/aymen/rp/lib/python3.7/site-packages/radical/utils/description.py", line 187, in verify
    if k not in schema: raise TypeError('key %s not in schema' % k)
TypeError: key argument not in schema
```
 with the following `RADICA-stack`:
```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aymen/rp

  radical.pilot        : 1.4.0-v1.4.0-48-gafbdfc3@devel
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0-v1.3.1-73-ga7accc7@devel
```

**Comment by AymenFJA** [comment]
Below is the failing session with the `devel stack` attached:

[rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007.zip](https://github.com/radical-cybertools/radical.pilot/files/4820797/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007.zip)

**Comment by mtitov** [comment]
@AymenFJA so yeah, looks like it is a different error now:
```
MT-MBP-X2:pilot.0000 matitov$ cat rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007.log
1592930939.361 : rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007 : 24408 : 140149033027328 : ERROR    : unusable lm MPIRUN
Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 171, in create
    return impl(name, cfg, session)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/mpirun.py", line 20, in __init__
    LaunchMethod.__init__(self, name, cfg, session)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 92, in __init__
    self._configure()
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/mpirun.py", line 72, in _configure
    self._get_mpi_info(self.launch_command)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-17-185.jetstream-cloud.org.aymen.018436.0007/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 384, in _get_mpi_info
    raise ValueError('no executable found')
ValueError: no executable found
```

and it might come from [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/mpirun.py#L71), will continue investigation

**Comment by andre-merzky** [comment]
The error message is correct: `argument` is not in the schema for the compute unit description (it should be `arguments`).
`argument` is only used in one example:
```sh
$ ack argument examples/| grep -v -e ': *#' -e arguments 
examples/probing.py:            cud.argument         =  ['/tmp/','>','$hostname.txt']
```
I assume this is what gves you trouble?  That should then be renamed `cud.arguments`.   Having said that, I think that example can safely be removed.

**Comment by andre-merzky** [comment]
PS.: the error `unusable lm MPIRUN` indicates that the launch method `MPIRUN` is not usable.  That is not a fatal error - but all MPI tasks will then fail to execute.  The log files near to that message will likely tell you more on why it is not usable - either RP does not know how to talk to your mpirun, or it does not find it at all.
