### ISSUE TITLE
Raptor masters are not operating within the targeted virtual environment 

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2489]
Facing an issue with `RAPTOR`, as the masters were not able to see/use the targeted `raptor_venv` prepared for them via the `pilot`.

```
Traceback (most recent call last):
  File "./raptor_master.py", line 9, in <module>
    import radical.utils as ru
ModuleNotFoundError: No module named 'radical'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[64112,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
```
  python               : /home/aymen/ve/raptor/bin/python3
  pythonpath           :
  version              : 3.7.6
  virtualenv           : /home/aymen/ve/raptor

  radical.gtod         : 1.6.7
  radical.pilot        : 1.11.2-v1.11.2-78-gc088983@feature-parsl_raptor_executor
  radical.saga         : 1.11.1
  radical.utils        : 1.11.0
```
Note that, `feature-parsl_raptor_executor` is a branch out from `feature/raptor_workers` branch.
Below is the pilot sandbox attached. 

[pilot.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/7974872/pilot.0000.zip)

**Comment by andre-merzky** [comment]
This should be resolved in https://github.com/radical-cybertools/radical.utils/pull/326

**Comment by andre-merzky** [comment]
@AymenFJA : Hey Aymen, what is the status on this?  #2495 and https://github.com/radical-cybertools/radical.utils/pull/326 should resolve this - do they?

**Comment by AymenFJA** [comment]
Hey @andre-merzky , the problem still exists. I have updated the tickets and the PR.

**Comment by AymenFJA** [comment]
As of now and with new commits reflected under the `raptor_workers` branch this issue is solved. I will reopen if needed,
