### ISSUE TITLE
radicalpilot-stats plot issues

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#504]
RP: feature/aimes-experiments
SP: devel
RU: devel

The plot created by `radicalpilot-stats -m plot` has the following issues:
* UNIT WAIT QUEUE SIZE is printed vertically on the right hand of the diagram 4 times. Should it be printed at all?
* Bottom third (pilot activity): the dotted lines indicating the amount of cores for each pilot overlap. Only one line remains visible.
* Middle third (unit states): a single line is created for all the CUs 
* Top third (pilot states): the 'line' of the pilots that do not become active stops at 'pending active'.

![run-256_late_uniform_1_55097d5c23769c16a8f2cace](https://cloud.githubusercontent.com/assets/2323492/6711544/079ed36a-cd5e-11e4-9e54-78fb81ab91d9.png)

**Comment by mturilli** [comment]
These issues were not addressed in the 0.28 release but new issues were added:
* The command exits with the following error:
  ```
$ radicalpilot-stats -d mongodb://54.221.194.147:24242/radicalpilot/ -m plot,stat -s rp.session.ip-10-184-31-85.mturilli.016546.0001                                                                                                                                                        
timestamp zero: 1429648631.36
modes   : plot,stat
db url  : mongodb://54.221.194.147:24242/radicalpilot/
cachedir: /home/mturilli/testing/RP
session : rp.session.ip-10-184-31-85.mturilli.016546.0001
no slot configuration for session rp.session.ip-10-184-31-85.mturilli.016546.0001
Please enable benchmarking: export RADICAL_PILOT_BENCHMARK=
no pilot callbacks
no pilot callbacks

plotting...
pilot_num       : 3
pilot_id_list   : pilot.0002 pilot.0000 pilot.0001 
pilot_name_list : gordon[20] blacklight[20] stampede[20] 

pilot name      : gordon[20]
pilot id        : pilot.0002

pilot name      : blacklight[20]
pilot id        : pilot.0000

pilot name      : stampede[20]
pilot id        : pilot.0001
./rp.session.ip-10-184-31-85.mturilli.016546.0001.pdf
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
./rp.session.ip-10-184-31-85.mturilli.016546.0001.png
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
line 296: warning: Skipping data file with no valid points
Traceback (most recent call last):
  File "/home/mturilli/Virtualenvs/RP-0.28/bin/radicalpilot-stats", line 1066, in <module>
    elif m == 'stat' : stat_session  (db, session, cachedir)
  File "/home/mturilli/Virtualenvs/RP-0.28/bin/radicalpilot-stats", line 368, in stat_session
    stats      = get_stats (docs, events, slothists)
  File "/home/mturilli/Virtualenvs/RP-0.28/bin/radicalpilot-stats", line 332, in get_stats
    pilot_runtime = (doc['finished'] - doc['started']) * pilot_info['cores']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
  ```
* Maybe due to this error, the diagram is missing the pilot(s) activity bars.
* The number of cores in the legend are repeated. It would be useful to distinguish between cores allocation and units executed or maybe between cores requested and cores used but I think the former would be more useful.
![rp session ip-10-184-31-85 mturilli 016546 0001](https://cloud.githubusercontent.com/assets/2323492/7262238/017a01f0-e846-11e4-997a-202651858657.png)

**Comment by andre-merzky** [comment]
Matteo, the issues have now been addressed in devel over several commits -- feedback welcome!

> * Middle third (unit states): a single line is created for all the CUs

I can't reproduce this problem.  Also, the plot you include in the last update shows distinct lines for units AFAICS.  So, is that gone by now?

> * Top third (pilot states): the 'line' of the pilots that do not become active stops at 'pending active'.

Alas, that is something I cannot easily fix, but a fix will emerge with upcoming pilot state changes...

**Comment by mturilli** [comment]
I pulled devel and it seems to be working fine, thank you.

Some of the the issues with the diagram persist. Here a summary:

> * UNIT WAIT QUEUE SIZE is printed vertically on the right hand of the diagram 4 times. Should it be printed at all?

Not addressed.

> * Bottom third (pilot activity): the dotted lines indicating the amount of cores for each pilot overlap. Only one line remains visible.

Addressed.

> * Middle third (unit states): a single line is created for all the CUs

Not addressed. Note that the session depicted in the attached plot has 8 units, not 2.

> * Top third (pilot states): the 'line' of the pilots that do not become active stops at 'pending active'.

Not addressed. I guess for this one we can wait.

> * Bottom third: the diagram is missing the pilot(s) activity bars.

Not addressed.

> * The number of cores in the legend are repeated.

Not addressed.

I hope this helps.
![run-8_late_uniform_1_rp session ip-10-184-31-85 mturilli 016546 0003](https://cloud.githubusercontent.com/assets/2323492/7264762/76fa8744-e85d-11e4-80ec-bc45d1a221f1.png)

**Comment by mturilli** [comment]
I have run another test with the latest commits on 0.28-devel. Here the issues still not addressed:
* Middle third (unit states): a single line is created for all the CUs
* Bottom third: the diagram is missing the pilot(s) activity bars.
![rp session ip-10-184-31-85 mturilli 016546 0004](https://cloud.githubusercontent.com/assets/2323492/7265473/72f8c89e-e868-11e4-9f85-2ba9cbd34f4e.png)

**Comment by andre-merzky** [comment]
> Middle third (unit states): a single line is created for all the CUs

I think that is really just a zooming issue.  If you look at a larger magnification, you'll see multiple lines close together.  The pilot seems to run two batches of 4 units each, and those 4 units have very similar timings.  The overall time on the x-axis is 1900 seconds -- starting those 4 units should be about 1 second, so I don't expect the plot to be able to resolve that much better than it does right now.

> Bottom third: the diagram is missing the pilot(s) activity bars.

Thanks, I'll look into this.

**Comment by andre-merzky** [comment]
The plot of used slots should be fixed now, too -- would you mind giving it another try?  Thanks!

**Comment by mturilli** [comment]
Lines now are visible but they seem a bit off or maybe I am missing something. I should have two groups of 5 lines and I am not sure why they go up to 30.
![run-8_late_uniform_1_rp session ip-10-184-31-85 mturilli 016547 0000](https://cloud.githubusercontent.com/assets/2323492/7273082/28035a2e-e8be-11e4-9183-04cf3229b892.png)

**Comment by andre-merzky** [comment]
You are running CUs of 2,4,8 and 16 cores -- in total you need, if I am not mistaken, 60 cores.  The pilot requests 20 cores, but gets 32 (nodesize on gordon is 16).  Thus RP manages to start some CUs so that 32 cores are used in the first batch, that leaves 28 cores for the second batch, which is what the plot shows I think.  Note that core numbering starts at 0.

**Comment by mturilli** [comment]
Thank you for the explanation. Shuould the legend and the corresponding dashed lines be set to 32 then (and whatever other amount of cores we get on blacklight/stampede)?

**Comment by andre-merzky** [comment]
Not sure, depends what we want.  At the moment, the line reflects the 'requested' size, but we can also let it mean the 'used' size.  That in turn would make the lines for inactive pilots zero...  I am fine either way, both versions are 'correct' ...

**Comment by mturilli** [comment]
The third way would be to set the values and the lines to the actual number of cores that have been obtained via the scheduler of the remote resource --- in this case 32 for each pilot even if we asked for 20. 

We have: 

1. number of cores requested, 
2. number of cores obtained, 
3. number of cores utilized. 

The first value depends on the pilot description and as this is an execution diagram is not too relevant IMHO. The second is actually the number of cores that the jobs on the remote machines asked and obtained. This is part of the execution. The third value is showed in the diagram by the CU lines in the bottom third of the diagram. For this reason, I think we should indicate the second value between square brackets and with the dashed line.

Related: is there a way to know how many cores have been actually assigned to a pilot via API while running RP?

**Comment by andre-merzky** [comment]
Until the pilot is running, we cannot know for sure how many cores it gets I think.  We derive that number from the environment of the *running* pilot process.  Also, for a pilot which never gets active, the 'obtained' set of cores is semantically indeed empty -- I would hesitate to set a number of cores which it 'might have gotten'.

You can inspect the number of obtained cores as `pilot.cores`, and it is also waht gets listed in the data frames.

**Comment by mturilli** [comment]
Let's go for used size then and I think we will have a clear semantic for this diagram :) Thank you for your patience.

**Comment by andre-merzky** [comment]
:)

**Comment by marksantcroos** [comment]
> Let's go for used size then

+1

**Comment by andre-merzky** [comment]
this is pushed now.

**Comment by andre-merzky** [comment]
All issues are addressed by now.  Further features will have to wait until plotting is migrated to data frames / matplotlib.
