### ISSUE TITLE
radical pilot failing on archer

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#581]
```
[Callback]: ComputeUnit 'unit.000000' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000001' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000002' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000003' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000004' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000005' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000006' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000007' state changed to PendingInputStaging.
[Callback]: ComputePilot 'pilot.0000' state changed to PendingActive.
[Callback]: ComputePilot 'pilot.0000' state changed to Done.
[Callback]: ComputeUnit 'unit.000005' state changed to Canceled.
```

agent.err:
```
--------------------------------------------------------------------------------
This is a private computing facility. Access to this system is limited to those
who have been granted access by the operating service provider on behalf of the
issuing authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------
Permission denied (publickey,keyboard-interactive).^M
=>> PBS: job killed: walltime 1202 exceeded limit 1200
kill: 13812: No such process
kill: 27805: No such process
pilot_bootstrapper.sh: line 102: 27805 Terminated              sleep 1
```

agent.out: https://gist.github.com/vivek-bala/d074929cec5f21a6f86d

**Comment by andre-merzky** [comment]
It should work again now. There was a problem with the permissions of a lock file. That requires a code fix, which I'll try to push as quickly as possible.

Thanks!

**Comment by marksantcroos** [comment]
I can't rime your fix with the "permission denied" error ...
Whats up there?

**Comment by andre-merzky** [comment]
line 185 is the interesting one: changing `rm` to `rm -f`.  The chmod is not essential, but leads to a better error message, as it reports the locking process.  The shortened timeout seems prudent for simple virtenv checking, loading or updating -- I am testing longer timeouts on `virtenv_create` though.  The enmd  folx used pilots which were running shorter than our lock timeout, and thus timed out before even having the chance of removing stale locks...

**Comment by andre-merzky** [comment]
This issue should be addressed now -- we pushed a fixed release (0.29) to pypi.

**Comment by vivek-bala** [comment]
I am still facing an issue. The error log is a bit different though.

```
(extasy-tools)vivek@ip-10-184-31-85:~/experiments/coam-on-archer$ RADICAL_PILOT_VERBOSE='debug' SAGA_VERBOSE='debug' extasy --RPconfig archer.rcfg --Kconfig cocoamber.wcfg 2> extasy.log
timestamp zero: 1430222494.64
ExTASY version :  0.1.4-beta
Session UID: rp.session.ip-10-184-31-85.vivek.016553.0000 
Pilot UID       : pilot.0000 
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/mmpbsa.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/coco.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/namd.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/lsdmap.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/amber.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/gromacs.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/sleep.json
Loading kernel configurations from /experiments/vivek/extasy-tools/lib/python2.7/site-packages/radical/ensemblemd/mdkernels/configs/test.json
Preprocessing stage ....
[Callback]: ComputePilot 'pilot.0000' state changed to Launching.
Cycle : 0
Skipping Analysis for iteration 0
Starting Simulation
[Callback]: ComputeUnit 'unit.000001' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000002' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000005' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000006' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000003' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000007' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000000' state changed to PendingInputStaging.
[Callback]: ComputeUnit 'unit.000004' state changed to PendingInputStaging.
[Callback]: ComputePilot 'pilot.0000' state changed to PendingActive.
[Callback]: ComputePilot 'pilot.0000' state changed to Done.
[Callback]: ComputeUnit 'unit.000001' state changed to Canceled.
#######################
##       ERROR       ##
#######################
ComputeUnit unit.000001 was canceled prematurely because the pilot was terminated. Can't recover.
Execution was interrupted
Closing session, exiting now ...
(extasy-tools)vivek@ip-10-184-31-85:~/experiments/coam-on-archer$ radicalpilot-version
timestamp zero: 1430223167.54
0.29
```


Agent.err:
```
--------------------------------------------------------------------------------
This is a private computing facility. Access to this system is limited to those
who have been granted access by the operating service provider on behalf of the
issuing authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------
Permission denied (publickey,keyboard-interactive).^M
/var/spool/PBS/mom_priv/jobs/2864960.sdb.SC: line 15: 25530 Segmentation fault      (core dumped) /bin/bash -l pilot_bootstrapper.sh -b 'radical.utils-0.28.tar.gz:saga-python-0.28.tar.gz:radical.pilot-0.29.tar.gz' -c '24' -d '10' -g '/work/e290/shared/shared_pilot_ve_20150325' -j 'APRUN' -k 'APRUN' -l 'PBSPRO' -m 'extasy-db.epcc.ed.ac.uk:27017' -n 'radicalpilot' -o 'POPEN' -p 'pilot.0000' -q 'CONTINUOUS' -r '20' -s 'rp.session.ip-10-184-31-85.vivek.016553.0000' -t 'multicore' -u 'use' -v 'debug' -a 'extasy:extasyproject' -e 'module load python' -f '10.60.0.52'
```

agent.out: https://gist.github.com/vivek-bala/6a03812c6ed6e9a09356

**Comment by vivek-bala** [comment]
I tried to run ExTASY on archer again. It again fails for me with a similar error in the agent.

agent.err:
```
> cat agent.err 
pilot_bootstrapper.sh: line 1230: unalias: pip: not found
--------------------------------------------------------------------------------
This is a private computing facility. Access to this system is limited to those
who have been granted access by the operating service provider on behalf of the
issuing authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------
Permission denied (publickey,keyboard-interactive).
pilot_bootstrapper.sh: line 573: unalias: pip: not found
Traceback (most recent call last):
  File "/fs4/e290/shared/shared_pilot_ve_20150429/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/work/y07/y07/cse/python/2.7.6-ucs4/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_Concat
Traceback (most recent call last):
  File "/fs4/e290/shared/shared_pilot_ve_20150429/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/work/y07/y07/cse/python/2.7.6-ucs4/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_Concat
Traceback (most recent call last):
  File "/fs4/e290/shared/shared_pilot_ve_20150429/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/work/y07/y07/cse/python/2.7.6-ucs4/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_Concat
Traceback (most recent call last):
  File "/fs4/e290/shared/shared_pilot_ve_20150429/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/work/y07/y07/cse/python/2.7.6-ucs4/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_Concat
Python 2.7.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016555.0001-pilot.0000/rp_install/lib/python2.7/site-packages/radical/__init__.py", line 2, in <module>
    import pkg_resources
  File "/fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/work/y07/y07/cse/python/2.7.6-ucs4/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_Concat
kill: 9890: No such process
```

agent.out: https://gist.github.com/vivek-bala/d5a964da35a29f9526fd
